version: "3.8"

services:
  datalex-db:
    image: postgres:15-alpine
    ports:
      - "5444:5432"
    environment:
      "PGDATA": "/var/lib/postgresql/data/pgdata"
      "POSTGRES_DB": "datalex"
      "POSTGRES_PASSWORD": "datalex"
      "POSTGRES_USER": "datalex"
      "POTGRES_PORT": 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  datalex:
    ports:
      - "8000:8000"
    image: datalex:latest
    build:
      context: .
    depends_on:
      - datalex-db
    volumes:
      - .:/app
    environment:
      DB_NAME: "datalex"
      DB_USER: "datalex"
      DB_PASSWORD: "datalex"
      DB_HOST: "datalex-db"
